package com.hefengbao.kmp.demo.calendar.db

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import java.io.File

/**
 * Creates or returns the singleton Room [AppDatabase] instance for JVM Desktop.
 * Uses [BundledSQLiteDriver] backed by a file in the user home directory so that
 * data persists across application restarts.
 *
 * Note: [AppDatabase_Impl] is generated by Room's KSP annotation processor at build time.
 */
object DatabaseFactory {
    @Volatile
    private var instance: AppDatabase? = null

    fun getDatabase(): AppDatabase =
        instance ?: synchronized(this) {
            instance ?: buildDatabase().also { instance = it }
        }

    private fun buildDatabase(): AppDatabase {
        val dbFile = File(System.getProperty("user.home"), ".kmp-demo-calendar.db")
        return Room.databaseBuilder<AppDatabase>(
            name = dbFile.absolutePath,
            factory = ::AppDatabase_Impl,
        )
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()
    }
}

/** Convenience top-level function for use in platform-specific Koin modules. */
fun createRoomDatabase(): AppDatabase = DatabaseFactory.getDatabase()
